# fly.toml app configuration file generated for classic-reader on 2025-03-11T20:52:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'classic-reader'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'on-failure'
  retries = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
